// would be generated with grunt, but static for now...

angular.module('ngd3', ['ngd3.services', 'ngd3.linegraph', 
                        'ngd3.axis']);

// and all code from src modules would go here...